### ISSUE TITLE
Possible GEOS version vulnerability (3.7.2)

### ISSUE THREAD

**Issue by rsbivand** [USGS-R/inlmisc#106]
Running reverse dependency checks on rgdal, I've hit an error 

```
Error in RGEOSBinTopoFunc(spgeom1, spgeom2, byid, id, drop_lower_td, unaryUnion_if_byid_false,  : 
  TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 2 3 at 2 3
```
in the Grid2Polygons() example. It occurs in `sp.polys.df <- raster::crop(sp.polys.df, ply)` which uses **rgeos**. My GEOS is 3.7.2-CAPI-1.11.2.

**Comment by jfisher-usgs** [comment]
Thank you for bringing this to my attention. The error has been fixed in the latest version (0.4.7) of inlmisc.
