### ISSUE TITLE
How to use GetColors in ggplot ecosystem ?

### ISSUE THREAD

**Issue by maedat** [USGS-R/inlmisc#132]
Thank you for your great tools!

I am getting some trouble to use your color schemes on ggplot.
Obtained object format with inlmisc::GetColors() seems to be different depend on the presence/absence of "scheme =" option. 

Here is an example 
```
 cols <- inlmisc::GetColors(n=6)
 cols 
```
> [1] "#E7EBFA" "#92559E" "#4F97BA" "#A1BE58" "#E5702F" "#521913"
> attr(,"nan")
> [1] "#666666"
> attr(,"call")
> GetColors(n = 6, scheme = "smooth rainbow", alpha = NULL, stops = c(0, 
> 1), bias = 1, reverse = FALSE, blind = NULL, gray = FALSE)
> attr(,"class")
> [1] "inlpal"    "character"

```
 cols_o <- inlmisc::GetColors(n=6,  scheme = "bright")
cols_o
```

>      blue       red     green    yellow      cyan    purple 
> "#4477AA" "#EE6677" "#228833" "#CCBB44" "#66CCEE" "#AA3377" 
> attr(,"nan")
> [1] NA
> attr(,"call")
> GetColors(n = 6, scheme = "bright", alpha = NULL, stops = c(0, 
> 1), bias = 1, reverse = FALSE, blind = NULL, gray = FALSE)
> attr(,"class")
> [1] "inlpal"    "character"

I want to use obtained color objects like this... 

```
g<-
  ggplot(iris,aes(x=Species, y =Sepal.Length, fill=Species))+
  geom_violin()

g+  scale_fill_manual(values=cols) # expected work
g+  scale_fill_manual(values=cols_o) # unexpected work

```

Do you have any plan to unify the output format or any idea around the situation?

**Comment by jfisher-usgs** [comment]
Hi Taro,

Thanks for bringing this to my attention. It looks like the “names” attribute on cols_o is causing the problem. Not sure why. The following is a work around…

g +  scale_fill_manual(values = as.character(cols_o))

All the best,
Jason

**Comment by maedat** [comment]
Thank you for your quick reply! 

I succeed in adopting the GetColors coloration with your help. Thanks a lot!
