### ISSUE TITLE
PlotCrossSection issue with extents

### ISSUE THREAD

**Issue by jsacerot** [USGS-R/inlmisc#142]
I am trying to plot the geologic cross-section between two layers using a raster stack with three elements: (1) elevation of layer 1, (2) elevation of layer 2, and (3) horizontal hydraulic conductivity of layer 1. Here is part of my code:

explanation <- "Horizontal Hydraulic Conductivity"
PlotCrossSection(transect, GW_stack, geo.lays = LE_names[c(1,2)],
                 val.lays = HK_names[1], 
                 ylab = "Elevation, m", asp = 5,
                 unit = "METERS", explanation = explanation,
                 bg.col = "#E1E1E1", bend.label = "BEND IN\nSECTION",
                 scale.loc = NULL)
AddScaleBar(unit = "HK, m/hr", vert.exag = 5, inset = 0.05)

PlotCrossSection is generating this error message: "Error in .local(x, y, ...) : extents do not overlap". I double-checked the extent of the three layers, and they are the same. How can I overcome this issue? Do the rasters need to have values all over the extent? or how the library handles rasters with certain areas with NA values?

Thanks!

**Comment by jfisher-usgs** [comment]
Hi Juan,

Thanks for submitting an issue. Could you provide me with the objects used in your example: `transect`, `GW_stack`, etc. That is, I'd like to re-create your error on my end. You could use the `save` function to store the objects in an `*.rda` file, or provide input files and read commands.

```r
explanation <- "Horizontal Hydraulic Conductivity"
PlotCrossSection(transect, GW_stack, geo.lays = LE_names[c(1,2)],
val.lays = HK_names[1],
ylab = "Elevation, m", asp = 5,
unit = "METERS", explanation = explanation,
bg.col = "#E1E1E1", bend.label = "BEND IN\nSECTION",
scale.loc = NULL)
AddScaleBar(unit = "HK, m/hr", vert.exag = 5, inset = 0.05)
```

Thanks,
Jason

**Comment by jsacerot** [comment]
Hi Jason,

Thank you for your prompt response. Please find attached the RData file with the objects that you need to recreate the issue. I think it may be related with the projection of the rasters in the stack. All have the same projection but PlotCrossSection does not like it.

[jfisher.zip](https://github.com/USGS-R/inlmisc/files/8290644/jfisher.zip)
 
 Cheers,
 
 Juan

**Comment by jfisher-usgs** [comment]
Fixes were merged into the "new" develop branch. To install:

```r
remotes::install_github("USGS-R/inlmisc@develop", dependencies = TRUE)
```
And here's the working function call and results:

```r
PlotCrossSection(
  transect,
  GW_stack,
  geo.lays = LE_names[c(1,2)],
  val.lays = HK_names[1],
  ylab = "Elevation, m",
  asp = 1000,
  unit = "METERS",
  explanation = "Horizontal Hydraulic Conductivity",
  bg.col = "#E1E1E1",
  bend.label = "BEND IN\nSECTION",
  scale.loc = NULL
)
```

![tmp](https://user-images.githubusercontent.com/681778/158905865-161aa162-78d7-49fe-a85c-012fc23255b4.png)

**Comment by jsacerot** [comment]
Hi Jason,

Thank you for fixing the problem. I am having problems installing the develop branch:

Running `R CMD build`...
* checking for file 'C:\Users\juanseba\AppData\Local\Temp\RtmpW4lgif\remotes311c17641e68\USGS-R-inlmisc-10f846b/DESCRIPTION' ... OK
* preparing 'inlmisc':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package 'inlmisc' ...
** using staged installation
** libs
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'inlmisc'
* removing 'C:/Users/juanseba/AppData/Local/Temp/RtmpA5PVlj/Rinst53a461905b79/inlmisc'
      -----------------------------------
ERROR: package installation failed
STDOUT:
* checking for file 'C:\Users\juanseba\AppData\Local\Temp\RtmpW4lgif\remotes311c17641e68\USGS-R-inlmisc-10f846b/DESCRIPTION' ... OK
* preparing 'inlmisc':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package 'inlmisc' ...
** using staged installation
** libs
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'inlmisc'
* removing 'C:/Users/juanseba/AppData/Local/Temp/RtmpA5PVlj/Rinst53a461905b79/inlmisc'
      -----------------------------------
ERROR: package installation failed
STDERR:

Error: Failed to install 'inlmisc' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.
In addition: Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package inlmisc has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\juanseba\Documents\R\win-library\4.1\00LOCK\Rcpp\libs\x64\Rcpp.dll to C:\Users\juanseba\Documents\R\win-library\4.1\Rcpp\libs\x64\Rcpp.dll: Permission denied

**Comment by jsacerot** [comment]
Hi Jason,

Thank you for fixing the issue. Now I am facing another problem when trying to plot more that two layers:

`explanation <- "Horizontal Hydraulic Conductivity"
PlotCrossSection(transect, GW_stack, geo.lays = LE_names[1:4],
                 val.lays = HK_names[1:3], 
                 ylab = "Elevation, m", asp = 500,
                 unit = "METERS", explanation = explanation,
                 bg.col = "#E1E1E1",
                 scale.loc = NULL)
AddScaleBar(unit = "HK, m/hr", vert.exag = 500, inset = 0.05)`

This is the generated error: 
"Error in sp::Polygons(cell.polys[which(cell.cols == cols[i])], i) : 
  length(srl) > 0 is not TRUE"

**Comment by jfisher-usgs** [comment]
Error should be resolved in the develop branch. The `breaks` argument may be what you're looking for with regard to limits on the color bar, that said, it's been awhile since I last got to play around with this function.

![tmp2](https://user-images.githubusercontent.com/681778/158923892-701fe0e0-76a0-4968-90c4-73d80c4f6652.png)

Thanks,
Jason

**Comment by jsacerot** [comment]
Thank you so much, Jason. It worked from my side. I think it would be helpful if there were another option to set the color bar limits in addition to the breaks option. The problem with the breaks is that it discretizes the color bar in several colors. However, sometimes you want to constrain values to certain lower and upper limits without losing the continuous color bar.

**Comment by jfisher-usgs** [comment]
Juan, thank you for reporting these bugs! I'll look into adding color-bar limits, or at least come up with a better solution for you.
