### ISSUE TITLE
`PlotMap()` relying on bugous  `range(NA, finite=TRUE)`

### ISSUE THREAD

**Issue by mmaechler** [USGS-R/inlmisc#49]
As was noted a few days ago on the R-devel mailing list,
https://stat.ethz.ch/pipermail/r-devel/2017-October/075037.html
that R's behavior for   `range(c(TRUE,FALSE,NA), finite=TRUE)`  has been wrongly returning
two NA's, e.g. as opposed to  `range( as.numeric(c(TRUE,FALSE,NA)), finite=TRUE)`  

In the mean time I (as R Core member)  have fixed this bug in the development version of R and yesterday have ported the patch to "R 3.4.2 patched" (planned to become R 3.4.3 soonish).

Unfortunately, your PlotMap() function has been relying on this buggy behavior in a way that it now (after the change) fails.

I now see you've fixed this yesterday, by removing `finite=TRUE` from
https://github.com/USGS-R/inlmisc/blob/master/R/PlotMap.R#L265
However I'd encourage a slightly different change (because you do want to get rid of +/- Inf  I think:

```

  if (anyNA(r[])) {
    n <- 0
  } else {
    zran <- range(r[], finite=TRUE)
```
But of course it's your call and code.
In any case, it will be good to upload a new version of the package to CRAN.

Best regards,
Martin Maechler

**Comment by jfisher-usgs** [comment]
Fixed in the latest version (inlmisc 0.3.5), thanks
