### ISSUE TITLE
The example of ReadCodeChunks

### ISSUE THREAD

**Issue by yihui** [USGS-R/inlmisc#57]
Do you mind using an Rmd file of your own?
 
https://github.com/USGS-R/inlmisc/blob/360c366e59dd54e3a31937eb9cd04d8c859a6783/R/ReadCodeChunks.R#L28

I'm asking because this will make it difficult for me to rename the file in the future, although it should be unlikely. Thanks!

**Comment by jfisher-usgs** [comment]
Good point, made the appropriate changes.
